name: Build wheels

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install celer
        run: |
          pip install numpy==1.21
          pip install -e .

      - name: Build source dist for ubuntu and macOS
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          python3 -m pip install --upgrade build
          python3 -m build --sdist

      - name: Build source dist for windows
        if: matrix.os == 'windows-latest'
        run: |
          py -m pip install --upgrade build
          py -m build --sdist

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_BUILD: >
            cp38-manylinux_x86_64 cp39-manylinux_x86_64 cp310-manylinux_x86_64
            cp38-macosx_x86_64    cp39-macosx_x86_64    cp310-macosx_x86_64
            cp38-win_amd64        cp39-win_amd64        cp310-win_amd64
        with:
          package-dir: .
          output-dir: wheelhouse

      - name: Inspect wheelhouse
        run: ls wheelhouse

      # - name: publish to Test PyPI
      #   env:
      #     TWINE_USERNAME: __token__
      #     TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #   run: |
      #     pip install twine
      #     twine upload --skip-existing --repository testpypi wheelhouse/*.whl dist/*.tar.gz

      - name: publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --skip-existing wheelhouse/*.whl dist/*.tar.gz